apiVersion: v1
kind: ConfigMap
metadata:
  name: data
  namespace: test
data:
{{/*      key: "{{  (lookup "v1" "ConfigMap" "test" "look").metadata.name }}"*/}}
  key2: "{{getHostByName "www.google.com"}}"